outfile: main.o merge.o print.o read.o save.o sort.o swap.o add.o count.o delete.o reverse.o palindrome.o
	cc main.o merge.o print.o read.o save.o sort.o swap.o add.o count.o delete.o reverse.o palindrome.o -o outfile

main.o:main.c
	cc -c main.c
merge.o:merge.c
	cc -c merge.c
print.o:print.c
	cc -c print.c
read.o:read.c
	cc -c read.c
save.o:save.c
	cc -c save.c
sort.o:sort.c
	cc -c sort.c
swap.o:swap.c
	cc -c swap.c
add.o:add.c
	cc -c add.c
count.o:count.c
	cc -c count.c
delete.o:delete.c
	cc -c delete.c
reverse.o:reverse.c
	cc -c reverse.c
palindrome.o:palindrome.c
	cc -c palindrome.c
